apiUnderTest: geomark
strategyClassName: NominalAndErrorStrategy
#  {
#    "apisUnderTest": [
#      {
#        "apiName": "bookstore",
#        "strategyClassName": "NominalAndErrorStrategy"
#      },
#      {
#        "apiName": "roudyAPI",
#        "strategyClassName": "AnotherStrategyClassName"
#      }
#    ]
#  }
